### ISSUE TITLE
Testing in Emulators

### ISSUE THREAD

**Issue by FabioCB** [metova/Cappuccino#5]
Hi, 

I am using the animations plug-in to disable and enable the system animations, however when running the tests in the emulator it says Empty test suite. In real devices it runs the tests and disables/enables the animations . Is this a known issue ? Any idea on how to solve ?

Thanks

**Comment by trobalik** [comment]
I actually do most of my testing with emulators, so that's not the problem. As a guess, could you tell me which version of Android you're emulating? Per the [adb docs](https://developer.android.com/studio/command-line/shell.html#pm), the `adb shell pm grant <application id> <permission name>` command works differently on devices with API level 23+ than it does on devices with API 22 and below. If your emulator is set to 22 or below, try the following:

> On devices running Android 6.0 (API level 23) and higher, may be any permission declared in the app manifest. On devices running Android 5.1 (API level 22) and lower, must be an optional permission defined by the app.

**Comment by FabioCB** [comment]
Thanks for the help, the problem was that I had the ADB integration disabled in Android Studio. It is working fine now.
